#     _________________________________________________
# ___/ Usefull stuff you do WANT for all repositories. \________________________
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: debug-statements  # Python only!
  - id: fix-encoding-pragma  # Python only!
#     ____________________________________
# ___/ Codespell… Can be really annoying. \___________________________________
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
    args: [-L, 'usig,persistant']
#     __________________
# ___/ Python specific. \______________________________________________________
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  rev: v1.2.4
  hooks:
  - id: python-safety-dependencies-check
# Statically populate the known_third_party isort setting.
- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
  - id: seed-isort-config
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1   # Use the revision sha / tag you want to point at
  hooks:
  - id: isort
- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: check-poetry
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
  rev: v1.0.6
  hooks:
  - id: python-bandit-vulnerability-check
    args: [--verbose, --ini, .banditrc, -ll, --skip, 'B321,B402', --recursive, src/lib]
#     ______
# ___/ BASH \__________________________________________________________________
- repo: https://github.com/lovesegfault/beautysh
  rev: v6.2.1
  hooks:
  - id: beautysh
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: shellcheck
#     _______________
# ___/ Markdown lint \_________________________________________________________
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
    args: [--ignore, CHANGELOG.md, -s, .mdl_style.rb]
#     ___________________________
# ___/ Semantic commit messages. \_____________________________________________
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
#     ________________
# ___/ Docker linters \________________________________________________________
- repo: https://github.com/IamTheFij/docker-pre-commit
  rev: v2.1.0
  hooks:
  - id: docker-compose-check
#     ________________
# ___/ GHA linting    \________________________________________________________
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.16.1
  hooks:
  - id: check-jsonschema
    name: "Check GitHub Workflows"
    files: ^\.github/workflows/
    types: [yaml]
    args: ["--verbose", "--schemafile", "https://json.schemastore.org/github-workflow"]
