site_name: setupr
repo_url: https://github.com/worldr/setupr
site_url: https://worldr.github.io/setupr
site_description: Setupr ships the Worldr infrastructure.
site_author: Dr Yann Golanski

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Development: development.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
copyright: Maintained by Dr Yann Golanski.
theme:
  name: material
  favicon: assets/favicon.png
  feature:
    tabs: true
  palette:
    primary: slate
    accent: teal
  logo: assets/logo.png
  features:
    - navigation.instant
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
