# checkout-and-yarn/action.yml

name: 'run-checks'
description: 'Composite action to run checks for code formatting and to run the unittests.'
runs:
    using: 'composite'
    steps:

      - name: "Formatting checks"
        run: |
              source .venv/bin/activate
              task check-isort
              task check-black
              task check-flake8
        shell: bash

      - name: "Type hinting check"
        run: |
              source .venv/bin/activate
              task check-mypy
        shell: bash

      - name: "Documentation check"
        run: |
              source .venv/bin/activate
              task check-docs
        shell: bash

      - name: "Securiuty check"
        run: |
              source .venv/bin/activate
              task check-bandit
        shell: bash

      - name: "Cyclomatic complexity check"
        run: |
              source .venv/bin/activate
              task check-radon
        shell: bash

      - name: "Test with pytest"
        run: |
              source .venv/bin/activate
              task tests
        shell: bash
