on:
    pull_request:
        types: [opened, synchronize, reopened]

name: on-pull-request

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:

      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Set up the environment"
        uses: ./.github/workflows/setup-poetry-env

      - name: "Install Task"
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GH_TOKEN }}
          version: 3.x

      - name: "Run checks"
        uses: ./.github/workflows/run-checks

  tox:
    runs-on: ubuntu-latest
    needs: quality
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Set up the environment"
        uses: ./.github/workflows/setup-poetry-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Test with tox"
        run: |
          source .venv/bin/activate
          poetry add "tox-gh-actions==v2.9.1"
          tox

  coverage:
    runs-on: ubuntu-latest
    needs: tox
    steps:
      - name: "Reporting test coverage"
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          lcov-file: ./coverage.lcov
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
